name: commit/pr checks

on:
  push:
    paths:
      - 'driver/**'
      - 'rit.bash'
      - 'suites/**'
      - 'testcases/**'
  pull_request:
    paths:
      - 'driver/**'
      - 'rit.bash'
      - 'suites/**'
      - 'testcases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'rit.bash rit'
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: ./rit.bash rit

